/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AtkRouteImport } from './routes/atk'
import { Route as IndoorRouteImport } from './routes/indoor'
import { Route as KirRouteImport } from './routes/kir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as OutdoorRouteImport } from './routes/outdoor'
import { Route as UsersRouteImport } from './routes/users'
import { Route as IndoorIndexRouteImport } from './routes/indoor.index'
import { Route as IndoorBidangIdRouteImport } from './routes/indoor.$bidangId'
import { Route as KirIndexRouteImport } from './routes/kir.index'
import { Route as KirRoomIdRouteImport } from './routes/kir.$roomId'
import { Route as OutdoorIndexRouteImport } from './routes/outdoor.index'
import { Route as OutdoorSiteIdRouteImport } from './routes/outdoor.$siteId'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AtkRoute = AtkRouteImport.update({
  id: '/atk',
  path: '/atk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndoorRoute = IndoorRouteImport.update({
  id: '/indoor',
  path: '/indoor',
  getParentRoute: () => rootRouteImport,
} as any)
const KirRoute = KirRouteImport.update({
  id: '/kir',
  path: '/kir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const OutdoorRoute = OutdoorRouteImport.update({
  id: '/outdoor',
  path: '/outdoor',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndoorIndexRoute = IndoorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndoorRoute,
} as any)
const IndoorBidangIdRoute = IndoorBidangIdRouteImport.update({
  id: '/$bidangId',
  path: '/$bidangId',
  getParentRoute: () => IndoorRoute,
} as any)
const KirIndexRoute = KirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KirRoute,
} as any)
const KirRoomIdRoute = KirRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => KirRoute,
} as any)
const OutdoorIndexRoute = OutdoorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutdoorRoute,
} as any)
const OutdoorSiteIdRoute = OutdoorSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => OutdoorRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/atk': typeof AtkRoute
  '/indoor': typeof IndoorRouteWithChildren
  '/kir': typeof KirRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/outdoor': typeof OutdoorRouteWithChildren
  '/users': typeof UsersRoute
  '/indoor/$bidangId': typeof IndoorBidangIdRoute
  '/kir/$roomId': typeof KirRoomIdRoute
  '/outdoor/$siteId': typeof OutdoorSiteIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/indoor/': typeof IndoorIndexRoute
  '/kir/': typeof KirIndexRoute
  '/outdoor/': typeof OutdoorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/atk': typeof AtkRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/users': typeof UsersRoute
  '/indoor/$bidangId': typeof IndoorBidangIdRoute
  '/kir/$roomId': typeof KirRoomIdRoute
  '/outdoor/$siteId': typeof OutdoorSiteIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/indoor': typeof IndoorIndexRoute
  '/kir': typeof KirIndexRoute
  '/outdoor': typeof OutdoorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/atk': typeof AtkRoute
  '/indoor': typeof IndoorRouteWithChildren
  '/kir': typeof KirRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/outdoor': typeof OutdoorRouteWithChildren
  '/users': typeof UsersRoute
  '/indoor/$bidangId': typeof IndoorBidangIdRoute
  '/kir/$roomId': typeof KirRoomIdRoute
  '/outdoor/$siteId': typeof OutdoorSiteIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/indoor/': typeof IndoorIndexRoute
  '/kir/': typeof KirIndexRoute
  '/outdoor/': typeof OutdoorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/atk'
    | '/indoor'
    | '/kir'
    | '/login'
    | '/master'
    | '/outdoor'
    | '/users'
    | '/indoor/$bidangId'
    | '/kir/$roomId'
    | '/outdoor/$siteId'
    | '/rooms/$roomId'
    | '/indoor/'
    | '/kir/'
    | '/outdoor/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/atk'
    | '/login'
    | '/master'
    | '/users'
    | '/indoor/$bidangId'
    | '/kir/$roomId'
    | '/outdoor/$siteId'
    | '/rooms/$roomId'
    | '/indoor'
    | '/kir'
    | '/outdoor'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/atk'
    | '/indoor'
    | '/kir'
    | '/login'
    | '/master'
    | '/outdoor'
    | '/users'
    | '/indoor/$bidangId'
    | '/kir/$roomId'
    | '/outdoor/$siteId'
    | '/rooms/$roomId'
    | '/indoor/'
    | '/kir/'
    | '/outdoor/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AtkRoute: typeof AtkRoute
  IndoorRoute: typeof IndoorRouteWithChildren
  KirRoute: typeof KirRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  OutdoorRoute: typeof OutdoorRouteWithChildren
  UsersRoute: typeof UsersRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atk': {
      id: '/atk'
      path: '/atk'
      fullPath: '/atk'
      preLoaderRoute: typeof AtkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indoor': {
      id: '/indoor'
      path: '/indoor'
      fullPath: '/indoor'
      preLoaderRoute: typeof IndoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kir': {
      id: '/kir'
      path: '/kir'
      fullPath: '/kir'
      preLoaderRoute: typeof KirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outdoor': {
      id: '/outdoor'
      path: '/outdoor'
      fullPath: '/outdoor'
      preLoaderRoute: typeof OutdoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indoor/': {
      id: '/indoor/'
      path: '/'
      fullPath: '/indoor/'
      preLoaderRoute: typeof IndoorIndexRouteImport
      parentRoute: typeof IndoorRoute
    }
    '/indoor/$bidangId': {
      id: '/indoor/$bidangId'
      path: '/$bidangId'
      fullPath: '/indoor/$bidangId'
      preLoaderRoute: typeof IndoorBidangIdRouteImport
      parentRoute: typeof IndoorRoute
    }
    '/kir/': {
      id: '/kir/'
      path: '/'
      fullPath: '/kir/'
      preLoaderRoute: typeof KirIndexRouteImport
      parentRoute: typeof KirRoute
    }
    '/kir/$roomId': {
      id: '/kir/$roomId'
      path: '/$roomId'
      fullPath: '/kir/$roomId'
      preLoaderRoute: typeof KirRoomIdRouteImport
      parentRoute: typeof KirRoute
    }
    '/outdoor/': {
      id: '/outdoor/'
      path: '/'
      fullPath: '/outdoor/'
      preLoaderRoute: typeof OutdoorIndexRouteImport
      parentRoute: typeof OutdoorRoute
    }
    '/outdoor/$siteId': {
      id: '/outdoor/$siteId'
      path: '/$siteId'
      fullPath: '/outdoor/$siteId'
      preLoaderRoute: typeof OutdoorSiteIdRouteImport
      parentRoute: typeof OutdoorRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IndoorRouteChildren {
  IndoorBidangIdRoute: typeof IndoorBidangIdRoute
  IndoorIndexRoute: typeof IndoorIndexRoute
}

const IndoorRouteChildren: IndoorRouteChildren = {
  IndoorBidangIdRoute: IndoorBidangIdRoute,
  IndoorIndexRoute: IndoorIndexRoute,
}

const IndoorRouteWithChildren =
  IndoorRoute._addFileChildren(IndoorRouteChildren)

interface KirRouteChildren {
  KirRoomIdRoute: typeof KirRoomIdRoute
  KirIndexRoute: typeof KirIndexRoute
}

const KirRouteChildren: KirRouteChildren = {
  KirRoomIdRoute: KirRoomIdRoute,
  KirIndexRoute: KirIndexRoute,
}

const KirRouteWithChildren = KirRoute._addFileChildren(KirRouteChildren)

interface OutdoorRouteChildren {
  OutdoorSiteIdRoute: typeof OutdoorSiteIdRoute
  OutdoorIndexRoute: typeof OutdoorIndexRoute
}

const OutdoorRouteChildren: OutdoorRouteChildren = {
  OutdoorSiteIdRoute: OutdoorSiteIdRoute,
  OutdoorIndexRoute: OutdoorIndexRoute,
}

const OutdoorRouteWithChildren =
  OutdoorRoute._addFileChildren(OutdoorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AtkRoute: AtkRoute,
  IndoorRoute: IndoorRouteWithChildren,
  KirRoute: KirRouteWithChildren,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  OutdoorRoute: OutdoorRouteWithChildren,
  UsersRoute: UsersRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
